export const APP_ROUTES = {
    Splash: "/",
    Login: "/login",
    SignUp: "/login/signUp",
    SignUpDetail: "/signup-details",
    Dashboard: "/dashboard",
    Activation: "/activation",
    EditProfile: "/dashboard/profileEdit",
    ShoppingCard: "/dashboard/shoppingCart",
    Invoices: "/dashboard/:oprAddress/invoices",
    Requests: "/dashboard/:oprAddress/requests",
    Service: "/dashboard/:oprAddress/services",
    Enrollservice: "/dashboard/:oprAddress/enrollservice",
    EnrollEmergencyService: "/dashboard/:oprAddress/emergency",
    ServiceItem: "/dashboard/serviceItem",
    ServiceItemEmergency: "/dashboard/serviceItemEmergency",
    Address: "/dashboard/newAddress",
};